export const SUCCESSFUL_REGISTRATION = "SUCCESSFUL_REGISTRATION";
export const ERROR_REGISTRATION = "ERROR_REGISTRATION";
export const CLEAR_ALERTS = "CLEAR_ALERTS";
export const USER_AUTHENTICATED = "USER_AUTHENTICATED";