export const REGISTRATION = "REGISTRATION";
export const SUCCESSFUL_REGISTRATION = "SUCCESSFUL_REGISTRATION";
export const ERROR_REGISTRATION = "ERROR_REGISTRATION";

export const LOGIN = "LOGIN";
export const SUCCESSFUL_LOGIN = "SUCCESSFUL_LOGIN";
export const ERROR_LOGIN = "ERROR_LOGIN";

export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const LOG_OUT = "LOG_OUT";

export const CLEAR_ALERTS = "CLEAR_ALERTS";
export const SHOW_ALERTS = "SHOW_ALERTS";

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_ERROR = "UPLOAD_FILE_ERROR";

export const CREATE_FILE_SUCCESS = "CREATE_FILE_SUCCESS";
export const CREATE_FILE_ERROR = "CREATE_FILE_ERROR";

export const CLEAR_STATE = "CLEAR_STATE"