export const SUCCESSFUL_REGISTRATION = "SUCCESSFUL_REGISTRATION";
export const ERROR_REGISTRATION = "ERROR_REGISTRATION";

export const SUCCESSFUL_LOGIN = "SUCCESSFUL_LOGIN";
export const ERROR_LOGIN = "ERROR_LOGIN";

export const CLEAR_ALERTS = "CLEAR_ALERTS";

export const USER_AUTHENTICATED = "USER_AUTHENTICATED";
export const LOG_OUT = "LOG_OUT";